"""add_feedback_and_confidence_columns

Revision ID: b8bfc41520b3
Revises: f4g5h6i7j8k9
Create Date: 2026-05-30 11:12:54.301762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8bfc41520b3'
down_revision: Union[str, Sequence[str], None] = 'f4g5h6i7j8k9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'app_settings')"))
    if result.scalar():
        op.alter_column('app_settings', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('now()'))
    op.add_column('pr_analyses', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('pr_analyses', sa.Column('confidence_scores', sa.Text(), nullable=True))
    op.alter_column('pr_analyses', 'files_changed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pr_analyses', 'additions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pr_analyses', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pr_analyses', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pr_analyses', 'risk_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pr_analyses', 'estimated_review_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pr_analyses', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pr_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pr_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_github_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_unique_constraint(op.f('users_github_id_key'), 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pr_analyses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pr_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pr_analyses', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('pr_analyses', 'estimated_review_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pr_analyses', 'risk_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('pr_analyses', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pr_analyses', 'deletions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pr_analyses', 'additions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pr_analyses', 'files_changed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pr_analyses', 'confidence_scores')
    op.drop_column('pr_analyses', 'feedback')
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'app_settings')"))
    if result.scalar():
        op.alter_column('app_settings', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=True,
                   existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
